name: Update Combined JSON
on:
  push:
    paths: ["data/*.json"]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python merge.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update combined.json"
          file_pattern: "combined.json"
